import { Channel } from "./types";

export const CHANNELS: Channel[] = [
  {
    id: "kbs1",
    name: "KBS 1TV",
    logo: "https://iptv-org.github.io/logos/languages/kor/KBS1.png",
    streamUrl: "https://1tv.gscdn.kbs.co.kr/1tv_3.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly8xdHYuZ3NjZG4ua2JzLmNvLmtyLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NzgxOTc2OTl9fX1dfQ__&Key-Pair-Id=APKAICDSGT3Y7IXGJ3TA&Signature=nkdUFn6Nse9oNYebXcX9iJsJc7eZf-i420LCcyGc2etXhdB7dL5UAmjZaB~0pRsuqGz5E-~DG47a3UVCsKQqau7Xkbv-mcxs4ovNxPQDAnQYQJqo~4VYBvFU~ix2sew9oztTEeQhUpmQ7TgX-TN9K6p4ROY1T06b5kE2A0f1JlYqrCx4gquzYhd8DtcLcBkkSVLEb3AXqbiz3M8mEM3aaCbuadgqVuMEIa9GVODraQUoB7YeAAuLITQOZ26pGYD1yvQhBgnjV7x5dQoF-5cBPpYxqcNFzPsRX86aVWHOXntqI73aUvF9eMJj55vDFHKPyd7Z9gzKyHg4INkd-aGUPg__", 
    category: "Public",
    description: "대한민국 대표 공영 방송 KBS 1TV입니다. 뉴스, 시사, 다큐멘터리 등 고품격 공영 콘텐츠를 제공합니다.",
    quality: "FHD",
  },
  {
    id: "kbs2",
    name: "KBS 2TV",
    logo: "https://iptv-org.github.io/logos/languages/kor/KBS2.png",
    streamUrl: "https://2tv.gscdn.kbs.co.kr/2tv_1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly8ydHYuZ3NjZG4ua2JzLmNvLmtyLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NzgxOTc5NDh9fX1dfQ__&Key-Pair-Id=APKAICDSGT3Y7IXGJ3TA&Signature=BftnxvBvYfKhZCOBdfHvoBmr95d3BjXRA-SWbjIXHFQ8wwNL2rwsv-aqpWpBNM68E7Fg0257M0M2ukHvgylHupH3KTp~KWDyMEB~aXe6vTCdQWBuyJkm9XwXBNI8nz9QX0J1BJF35ei0ztJHgW61uXdTo94cVhJq3MsBAFy5KGqQ6UiGx9wYx~xeN6j05OdAg9H37HU8XAGrgxJEYO35dsQCT06B48sXFc057-Z3et5dSWJyZtqMa1lRVe8BALs9ksRUmDBDyStjBhkjMxfyMj3YKj5dwntlqjpeXuFX5D9iojmkY~t5pgzbcy7qzIxe-mRqk~ygFYlSMVxjJ94VaQ__",
    category: "Public",
    description: "다양한 예능과 드라마, 문화 프로그램을 즐길 수 있는 KBS 2TV입니다.",
    quality: "FHD",
  },
  {
    id: "mbc",
    name: "MBC",
    logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png",
    streamUrl: "https://mbc-hls.cdn.vcdn.com.vn/hls/mbc/index.m3u8",
    category: "Public",
    description: "만나면 좋은 친구 MBC입니다. 보도, 드라마, 예능 등 최상의 콘텐츠를 감상하세요.",
    quality: "FHD",
  },
  {
    id: "sbs",
    name: "SBS",
    logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png",
    streamUrl: "https://sbs-hls.cdn.vcdn.com.vn/hls/sbs/index.m3u8",
    category: "Public",
    description: "함께 만드는 기쁨, SBS입니다. 고화질 방송 송출을 통해 생생한 현장감을 전달합니다.",
    quality: "FHD",
  },
  {
    id: "sbs_golf",
    name: "SBS Golf",
    logo: "https://iptv-org.github.io/logos/languages/kor/SBSGolf.png",
    streamUrl: "https://tvlive.sbs.co.kr/sbsgolf/sbsgolf1.stream/playlist.m3u8?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NzgwMzM0NDksInBhdGgiOiIvc2JzZ29sZjEuc3RyZWFtIiwiZHVyYXRpb24iOi0xLCJ1bm8iOiJmY2JjYzc0NS02MTc2LTQzNmUtYmE5OC0xZmVjMWZhZTE3ZDEiLCJpYXQiOjE3NzgwMjYyNDl9.U3VWDQHCkZpYUTWPLjdKsAGB0Cz98jE_-FL4VvDWIZI",
    category: "Sports",
    description: "대한민국 No.1 골프 채널 SBS Golf입니다.",
    quality: "FHD",
  },
  {
    id: "sbs_sports",
    name: "SBS Sports",
    logo: "https://iptv-org.github.io/logos/languages/kor/SBSSports.png",
    streamUrl: "https://tvlive.sbs.co.kr/sbsespn/sbsespn1.stream/playlist.m3u8?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NzgwNDkzMTksInBhdGgiOiIvc2JzZXNwbjEuc3RyZWFtIiwiZHVyYXRpb24iOi0xLCJ1bm8iOiJmZjZmNWI5Mi1mMzk4LTQ5OGUtYmE5ZS0wZGU0NmJlNGFmOTUiLCJpYXQiOjE3NzgwNDIxMTl9.NI3ED4jy2yb5FNcTuF3DC1oG-8DjI2BZgd7LIoSgy6s",
    category: "Sports",
    description: "대한민국 No.1 스포츠 채널 SBS Sports입니다.",
    quality: "FHD",
  },
  {
    id: "jtbc",
    name: "JTBC",
    logo: "https://iptv-org.github.io/logos/languages/kor/JTBC.png",
    streamUrl: "https://jtbc-hls.cdn.vcdn.com.vn/hls/jtbc/index.m3u8",
    category: "General",
    description: "다채로운 즐거움 JTBC입니다. 뉴스룸, 예능, 드라마 등 트렌디한 콘텐츠를 제공합니다.",
    quality: "FHD",
  },
  {
    id: "jtbc_onair",
    name: "JTBC (온에어)",
    logo: "https://iptv-org.github.io/logos/languages/kor/JTBC.png",
    streamUrl: "https://onair.jtbc.co.kr/",
    category: "General",
    description: "JTBC 공식 온에어 페이지입니다. 영상 재생이 안 될 경우 'Open Source' 버튼을 활용하세요.",
    quality: "FHD",
  },
  {
    id: "tvchosun",
    name: "TV CHOSUN",
    logo: "https://iptv-org.github.io/logos/languages/kor/TVChosun.png",
    streamUrl: "https://tvchosun-hls.cdn.vcdn.com.vn/hls/tvchosun/index.m3u8",
    category: "General",
    description: "새로운 방송 TV CHOSUN입니다. 전국민적 사랑을 받는 예능과 뉴스를 실시간으로 시청하세요.",
    quality: "FHD",
  },
  {
    id: "channela",
    name: "Channel A",
    logo: "https://iptv-org.github.io/logos/languages/kor/ChannelA.png",
    streamUrl: "https://channela-hls.cdn.vcdn.com.vn/hls/channela/index.m3u8",
    category: "General",
    description: "꿈을 담는 캔버스 채널A입니다.",
    quality: "FHD",
  },
  {
    id: "ebs1",
    name: "EBS 1",
    logo: "https://iptv-org.github.io/logos/languages/kor/EBS1.png",
    streamUrl: "https://ebsonair.ebs.co.kr/groundwavefamilypc/familypc1m/playlist.m3u8",
    category: "Education",
    description: "교육의 중심 EBS 1TV입니다. 유아부터 성인까지 모두를 위한 교육 방송을 실시간으로 시청하세요.",
    quality: "FHD",
  },
  {
    id: "ebs2",
    name: "EBS 2",
    logo: "https://iptv-org.github.io/logos/languages/kor/EBS2.png",
    streamUrl: "https://ebsonair.ebs.co.kr/ebs2familypc/familypc1m/playlist.m3u8",
    category: "Education",
    description: "창의·융합 인재 양성을 위한 교육 채널 EBS 2TV입니다.",
    quality: "FHD",
  },
  {
    id: "ebs_p1",
    name: "EBS Plus 1",
    logo: "https://iptv-org.github.io/logos/languages/kor/EBSPlus1.png",
    streamUrl: "https://ebsonair.ebs.co.kr/plus1familypc/familypc1m/playlist.m3u8",
    category: "Education",
    description: "수능 및 고교 교육 전문 채널 EBS Plus 1입니다.",
    quality: "FHD",
  },
  {
    id: "ebs_p2",
    name: "EBS Plus 2",
    logo: "https://iptv-org.github.io/logos/languages/kor/EBSPlus2.png",
    streamUrl: "https://ebsonair.ebs.co.kr/plus2familypc/familypc1m/playlist.m3u8",
    category: "Education",
    description: "초등, 중등 및 직업 교육 전문 채널 EBS Plus 2입니다.",
    quality: "FHD",
  },
  {
    id: "ebs_e",
    name: "EBS English",
    logo: "https://iptv-org.github.io/logos/languages/kor/EBSEnglish.png",
    streamUrl: "https://ebsonair.ebs.co.kr/plus3familypc/familypc1m/playlist.m3u8",
    category: "Education",
    description: "24시간 영어 학습 전문 채널 EBS English입니다.",
    quality: "HD",
  },
  {
    id: "ebs_k",
    name: "EBS Kids",
    logo: "https://iptv-org.github.io/logos/languages/kor/EBSKids.png",
    streamUrl: "https://ebsonair.ebs.co.kr/ebsk/public/index.m3u8",
    category: "Education",
    description: "아이들의 꿈과 희망을 키우는 EBS Kids 채널입니다.",
    quality: "HD",
  },
  {
    id: "ytn",
    name: "YTN NEWS",
    logo: "https://iptv-org.github.io/logos/languages/kor/YTN.png",
    streamUrl: "https://www.youtube-nocookie.com/embed/aZyD6EPl6KU?autoplay=1&enablejsapi=1&rel=0",
    category: "News",
    description: "24시간 생생한 뉴스를 전달하는 대한민국 대표 뉴스 채널 YTN입니다.",
    quality: "FHD",
  },
  {
    id: "yonhap",
    name: "Yonhap News TV",
    logo: "https://iptv-org.github.io/logos/languages/kor/YonhapNewsTV.png",
    streamUrl: "https://www.youtube-nocookie.com/embed/6QZ_qc75ihU?autoplay=1&enablejsapi=1&rel=0",
    category: "News",
    description: "빠르고 정확한 뉴스를 전하는 연합뉴스TV입니다.",
    quality: "FHD",
  },
  {
    id: "cbs",
    name: "CBS TV",
    logo: "https://iptv-org.github.io/logos/languages/kor/CBS.png",
    streamUrl: "https://www.youtube-nocookie.com/embed/cxtw2RuOYac?autoplay=1&enablejsapi=1&rel=0",
    category: "News",
    description: "대한민국 대표 기독교 방송 CBS TV입니다.",
    quality: "FHD",
  },
  {
    id: "kbs_news",
    name: "KBS NEWS 24",
    logo: "https://iptv-org.github.io/logos/languages/kor/KBSNews24.png",
    streamUrl: "https://kbsnews-hls.cdn.vcdn.com.vn/hls/kbsnews/index.m3u8",
    category: "News",
    description: "KBS의 24시간 뉴스 전문 채널입니다.",
    quality: "HD",
  },
  {
    id: "arirang",
    name: "Arirang TV",
    logo: "https://iptv-org.github.io/logos/languages/kor/ArirangTV.png",
    streamUrl: "https://amdlive.akamaized.net/hls/live/707364/arirang_1/index.m3u8",
    category: "World",
    description: "대한민국의 소식을 전 세계에 알리는 국제 방송 Arirang TV입니다.",
    quality: "FHD",
  },
  {
    id: "kbs_world",
    name: "KBS WORLD",
    logo: "https://iptv-org.github.io/logos/languages/kor/KBSWorld.png",
    streamUrl: "https://kbs-world-hls.cdn.vcdn.com.vn/hls/kbsworld/index.m3u8",
    category: "World",
    description: "전 세계인을 대상으로 한 KBS의 글로벌 한류 채널입니다.",
    quality: "HD",
  },
  {
    id: "kbs_drama",
    name: "KBS Drama",
    logo: "https://iptv-org.github.io/logos/languages/kor/KBSDrama.png",
    streamUrl: "https://kbsdrama-hls.cdn.vcdn.com.vn/hls/kbsdrama/index.m3u8",
    category: "Drama",
    description: "KBS의 엄선된 드라마를 전문으로 방영하는 채널입니다.",
    quality: "HD",
  },
  {
    id: "kbs_joy",
    name: "KBS Joy",
    logo: "https://iptv-org.github.io/logos/languages/kor/KBSJoy.png",
    streamUrl: "https://kbsjoy-hls.cdn.vcdn.com.vn/hls/kbsjoy/index.m3u8",
    category: "Entertainment",
    description: "KBS의 다양한 예능 콘텐츠를 즐길 수 있는 엔터테인먼트 채널입니다.",
    quality: "HD",
  },
  {
    id: "mbc_net",
    name: "MBC Net",
    logo: "https://iptv-org.github.io/logos/languages/kor/MBCNet.png",
    streamUrl: "https://mbcnet-hls.cdn.vcdn.com.vn/hls/mbcnet/index.m3u8",
    category: "Public",
    description: "지역 문화와 삶의 향기를 전하는 MBC 지역 연합 채널입니다.",
    quality: "HD",
  },
  {
    id: "kbc",
    name: "KBC Gwangju",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/SMPTE_Color_Bars.svg/1024px-SMPTE_Color_Bars.svg.png",
    streamUrl: "https://www.youtube-nocookie.com/embed/4hpUbFP13-M?autoplay=1&enablejsapi=1&rel=0",
    category: "News",
    description: "내일의 희망을 만드는 KBC 광주방송입니다.",
    quality: "FHD",
  },
  {
    id: "test",
    name: "SIGNAL TEST",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/SMPTE_Color_Bars.svg/1024px-SMPTE_Color_Bars.svg.png",
    streamUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    category: "Debug",
    description: "플레이어 상태 점검을 위한 테스트 스트림입니다. 이 화면이 잘 보인다면 방송 소스의 문제입니다.",
    quality: "UHD",
  },
];
