import { Channel } from "./types";

export const CHANNELS: Channel[] = [
  // --- EBS ---
  { id: "ebs1", name: "EBS1", logo: "https://iptv-org.github.io/logos/languages/kor/EBS1.png", streamUrl: "https://ebsonair.ebs.co.kr/groundwavefamilypc/familypc1m/playlist.m3u8", category: "EBS", description: "교육의 중심 EBS 1TV", quality: "FHD" },
  { id: "ebs2", name: "EBS2", logo: "https://iptv-org.github.io/logos/languages/kor/EBS2.png", streamUrl: "https://ebsonair.ebs.co.kr/ebs2familypc/familypc1m/playlist.m3u8", category: "EBS", description: "창의·융합 교육 EBS 2TV", quality: "FHD" },
  { id: "ebs_kids", name: "EBS Kids", logo: "https://iptv-org.github.io/logos/languages/kor/EBSKids.png", streamUrl: "https://ebsonair.ebs.co.kr/ebsufamilypc/familypc1m/playlist.m3u8", category: "EBS", description: "어린이 전문 교육", quality: "HD" },
  { id: "ebs_p1", name: "EBS+1", logo: "https://iptv-org.github.io/logos/languages/kor/EBSPlus1.png", streamUrl: "https://ebsonair.ebs.co.kr/plus1familypc/familypc1m/playlist.m3u8", category: "EBS", description: "수능 교육 전문", quality: "HD" },
  { id: "ebs_p2", name: "EBS+2", logo: "https://iptv-org.github.io/logos/languages/kor/EBSPlus2.png", streamUrl: "https://ebsonair.ebs.co.kr/plus2familypc/familypc1m/playlist.m3u8", category: "EBS", description: "초/중등 교육 전문", quality: "HD" },
  { id: "ebs_e", name: "EBSe", logo: "https://iptv-org.github.io/logos/languages/kor/EBSEnglish.png", streamUrl: "https://ebsonair.ebs.co.kr/plus3familypc/familypc1m/playlist.m3u8", category: "EBS", description: "영어 교육 전문", quality: "HD" },
  { id: "ebs_fm", name: "EBS FM", logo: "https://iptv-org.github.io/logos/languages/kor/EBSFM.png", streamUrl: "https://ebsonair.ebs.co.kr/fmradiofamilypc/familypc1m/playlist.m3u8", category: "EBS", description: "교육 정보 라디오", quality: "HD" },
  { id: "ebs_bandi", name: "EBS bandi", logo: "https://iptv-org.github.io/logos/languages/kor/EBSFM.png", streamUrl: "https://ebsonair.ebs.co.kr/cloud1/iradio/playlist.m3u8", category: "EBS", description: "인터넷 라디오", quality: "HD" },

  // --- KBS ---
  { id: "kbs1", name: "KBS 1TV", kbsCode: "11", logo: "https://iptv-org.github.io/logos/languages/kor/KBS1.png", streamUrl: "", category: "KBS", description: "국가 기간 방송", quality: "FHD" },
  { id: "kbs2", name: "KBS 2TV", kbsCode: "12", logo: "https://iptv-org.github.io/logos/languages/kor/KBS2.png", streamUrl: "", category: "KBS", description: "즐거움과 감동", quality: "FHD" },
  { id: "kbs_world", name: "KBS World", kbsCode: "14", logo: "https://iptv-org.github.io/logos/languages/kor/KBSWorld.png", streamUrl: "", category: "KBS", description: "글로벌 한류 채널", quality: "HD" },
  { id: "kbs_newsd", name: "KBS 뉴스D", kbsCode: "81", logo: "https://iptv-org.github.io/logos/languages/kor/KBSNews24.png", streamUrl: "", category: "KBS", description: "실시간 뉴스 데이터", quality: "HD" },
  { id: "kbs_drama", name: "KBS Drama", kbsCode: "N91", logo: "https://iptv-org.github.io/logos/languages/kor/KBSDrama.png", streamUrl: "", category: "KBS", description: "KBS 드라마 정주행", quality: "HD" },
  { id: "kbs_joy", name: "KBS Joy", kbsCode: "N92", logo: "https://iptv-org.github.io/logos/languages/kor/KBSJoy.png", streamUrl: "", category: "KBS", description: "예능 전문 채널", quality: "HD" },
  { id: "kbs_life", name: "KBS Life", kbsCode: "N93", logo: "https://iptv-org.github.io/logos/languages/kor/KBSLife.png", streamUrl: "", category: "KBS", description: "생활 문화 정보", quality: "HD" },
  { id: "kbs_story", name: "KBS Story", kbsCode: "N94", logo: "https://iptv-org.github.io/logos/languages/kor/KBSStory.png", streamUrl: "", category: "KBS", description: "여성 교육/드라마 전문", quality: "HD" },
  { id: "kbs_kids_ch", name: "KBS Kids", kbsCode: "N96", logo: "https://iptv-org.github.io/logos/languages/kor/KBSKids.png", streamUrl: "", category: "KBS", description: "어린이 전문 교육", quality: "HD" },
  { id: "kbs_nvod1", name: "썸, 마이웨이", kbsCode: "nvod1", logo: "https://iptv-org.github.io/logos/languages/kor/KBS2.png", streamUrl: "", category: "KBS", description: "정주행 채널", quality: "HD" },
  { id: "kbs_nvod2", name: "태조왕건", kbsCode: "nvod2", logo: "https://iptv-org.github.io/logos/languages/kor/KBS1.png", streamUrl: "", category: "KBS", description: "정통 대하드라마", quality: "HD" },
  { id: "kbs_nvod3", name: "직장의 신", kbsCode: "nvod3", logo: "https://iptv-org.github.io/logos/languages/kor/KBS2.png", streamUrl: "", category: "KBS", description: "몰아보기 채널", quality: "HD" },
  { id: "kbs_nvod6", name: "1박 2일", kbsCode: "nvod6", logo: "https://iptv-org.github.io/logos/languages/kor/KBS2.png", streamUrl: "", category: "KBS", description: "예능 정주행", quality: "HD" },
  { id: "kbs_nvod9", name: "인간극장", kbsCode: "nvod9", logo: "https://iptv-org.github.io/logos/languages/kor/KBS1.png", streamUrl: "", category: "KBS", description: "휴먼 다큐 정주행", quality: "HD" },
  { id: "kbs_fm_cl", name: "KBS 클래식FM", kbsCode: "24", logo: "https://iptv-org.github.io/logos/languages/kor/KBS1.png", streamUrl: "", category: "KBS", description: "고품격 음악 라디오", quality: "HD" },
  { id: "kbs_fm_co", name: "KBS 쿨FM", kbsCode: "25", logo: "https://iptv-org.github.io/logos/languages/kor/KBS2.png", streamUrl: "", category: "KBS", description: "트렌디 대중음악", quality: "HD" },
  { id: "kbs_radio1", name: "KBS 1라디오", kbsCode: "21", logo: "https://iptv-org.github.io/logos/languages/kor/KBS1.png", streamUrl: "", category: "KBS", description: "뉴스 시사 전문", quality: "HD" },

  // --- MBC Regional & Radio ---
  { id: "mbc_gy_tv", name: "MBC 강원영동", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "http://123.254.93.7:1935/tvlive/livestream2/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },
  { id: "mbc_gy_sfm", name: "MBC 강원영동 표준FM", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "http://123.254.72.24:1935/amlive/livestream/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "mbc_gy_fm4u", name: "MBC 강원영동 FM4U", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "http://123.254.72.24:1935/fmlive/livestream/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "mbc_dg_tv", name: "MBC 대구", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://5ee1ec6f32118.streamlock.net/live/livetv/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },
  { id: "mbc_dg_sfm", name: "MBC 대구 표준FM", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://5ee1ec6f32118.streamlock.net/amradio/am/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "mbc_dg_fm4u", name: "MBC 대구 FM4U", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://5ee1ec6f32118.streamlock.net/fmradio/fm/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "mbc_dj_tv", name: "MBC 대전", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://5c482867a8b63.streamlock.net/live/myStream.sdp/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },
  { id: "mbc_dj_sfm", name: "MBC 대전 표준FM", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://5c482867a8b63.streamlock.net/live_am/live_am.stream/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "mbc_dj_fm4u", name: "MBC 대전 FM4U", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://5c482867a8b63.streamlock.net/live_fm/live_fm.stream/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "mbc_mp_tv", name: "MBC 목포", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://vod.mpmbc.co.kr/a_live/25246741/ch001/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },
  { id: "mbc_ys_tv", name: "MBC 여수", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://5c3639aa99149.streamlock.net/live_TV/tv/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },
  { id: "mbc_jj_tv", name: "MBC 전주", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://5ee9633b25727.streamlock.net:443/jmbc_tv/jmbc_tv.stream/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },
  { id: "mbc_jeju_tv", name: "MBC 제주", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://wowza.jejumbc.com/live/tv_jejumbc/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },
  { id: "mbc_cc_tv", name: "MBC 춘천", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "https://stream.chmbc.co.kr/TV/myStream/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },
  { id: "mbc_cb_tv", name: "MBC 충북", logo: "https://iptv-org.github.io/logos/languages/kor/MBC.png", streamUrl: "http://211.33.246.4:32954/cj_live/myStream.sdp/playlist.m3u8", category: "MBC", description: "지역 MBC", quality: "HD" },

  // --- SBS Regional & Radio ---
  { id: "sbs_g1", name: "G1 강원 TV", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "http://61.82.49.4:1935/live/_definst_/tv.stream/playlist.m3u8", category: "SBS", description: "SBS 네트워크", quality: "HD" },
  { id: "sbs_g1_fm", name: "G1 강원 FM", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "http://61.82.49.4:1935/fm/_definst_/myStream/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "sbs_kbc", name: "KBC 광주 TV", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://vod.ikbc.co.kr/KBCTV/tv/playlist.m3u8", category: "SBS", description: "SBS 네트워크", quality: "HD" },
  { id: "sbs_kbc_fm", name: "KBC 광주 FM", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://vod.ikbc.co.kr/KBCFM/kbcra_aac/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "sbs_knn", name: "KNN 부산경남", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://stream1.knn.co.kr/hls/9ly4534y7dm2xfa123r2_tv/index.m3u8", category: "SBS", description: "SBS 네트워크", quality: "HD" },
  { id: "sbs_knn_pfm", name: "KNN 파워FM", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://stream1.knn.co.kr/hls/lb9ezl87d37uu0vy65bb_pfm/index.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "sbs_knn_lfm", name: "KNN 러브FM", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://stream1.knn.co.kr/hls/b3y26uu6471k8tes9w7h_lfm/index.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "sbs_ubc", name: "UBC 울산 TV", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://stream.ubc.co.kr/hls/ubctvstream/index.m3u8", category: "SBS", description: "SBS 네트워크", quality: "HD" },
  { id: "sbs_ubc_fm", name: "UBC 울산 FM", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://stream.ubc.co.kr/hls/ubcfmstream/index.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "sbs_jtv", name: "JTV 전주 TV", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://61ff3340258d2.streamlock.net/jtv_live/myStream/playlist.m3u8", category: "SBS", description: "SBS 네트워크", quality: "HD" },
  { id: "sbs_jtv_fm", name: "JTV 전주 FM", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "https://61ff3340258d2.streamlock.net/jtv_radio/myStream/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "sbs_cjb", name: "CJB 청주 TV", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "http://1.222.207.80:1935/live/cjbtv/playlist.m3u8", category: "SBS", description: "SBS 네트워크", quality: "HD" },
  { id: "sbs_cjb_fm", name: "CJB 청주 FM", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "http://1.222.207.80:1935/live/cjbradio/playlist.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },
  { id: "sbs_jibs", name: "JIBS 제주 TV", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "http://123.140.197.22/stream/1/play.m3u8", category: "SBS", description: "SBS 네트워크", quality: "HD" },
  { id: "sbs_jibs_fm", name: "JIBS 제주 FM", logo: "https://iptv-org.github.io/logos/languages/kor/SBS.png", streamUrl: "http://123.140.197.22/stream/2/play.m3u8", category: "Radio", description: "지역 라디오", quality: "HD" },

  // --- Etc ---
  { id: "tvchosun", name: "TV CHOSUN", logo: "https://iptv-org.github.io/logos/languages/kor/TVChosun.png", streamUrl: "https://onaircdn.tvchosun.com/origin1/_definst_/tvchosun_s1/playlist.m3u8", category: "기타", description: "종합편성 채널", quality: "FHD" },
  { id: "tvchosun2", name: "TV CHOSUN 2", logo: "https://iptv-org.github.io/logos/languages/kor/TVChosun.png", streamUrl: "https://onair2cdn.tvchosun.com/origin2/_definst_/tvchosun_s1/playlist.m3u8", category: "기타", description: "TV CHOSUN의 유쾌한 변칙", quality: "FHD" },
  { id: "dema_tv", name: "국방TV", logo: "https://iptv-org.github.io/logos/languages/kor/NationalDefenseTV.png", streamUrl: "http://mediaworks.dema.mil.kr:1935/live_edge/cudo.sdp/playlist.m3u8", category: "기타", description: "국방 안보 전문 브리핑", quality: "HD" },
  { id: "dema_fm", name: "국방FM", logo: "https://iptv-org.github.io/logos/languages/kor/NationalDefenseTV.png", streamUrl: "http://mediaworks.dema.mil.kr:1935/live_edge/audio.sdp/playlist.m3u8", category: "Radio", description: "국방 전문 라디오", quality: "HD" },
  { id: "gugak_tv", name: "국악방송", logo: "https://iptv-org.github.io/logos/languages/kor/GugakTV.png", streamUrl: "http://mgugaklive.nowcdn.co.kr/gugakvideo/gugakvideo.stream/playlist.m3u8", category: "기타", description: "한국의 소리 전문 방송", quality: "HD" },
  { id: "gugak_radio", name: "국악방송 라디오", logo: "https://iptv-org.github.io/logos/languages/kor/GugakTV.png", streamUrl: "http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8", category: "Radio", description: "국악 전문 라디오", quality: "HD" },
  { id: "natv", name: "국회방송", logo: "https://iptv-org.github.io/logos/languages/kor/NATV.png", streamUrl: "https://m.webcast.go.kr/live/_definst_/smil:natv_720p.smil/playlist.m3u8", category: "기타", description: "국립 방송 및 국회 중계", quality: "HD" },
  { id: "dlive_seoul", name: "딜라이브TV 서울", logo: "https://iptv-org.github.io/logos/languages/kor/DLive.png", streamUrl: "http://112.214.255.230/hls/ch02/playlist.m3u8", category: "기타", description: "지역 생활 정보", quality: "HD" },
  { id: "dlive_gg", name: "딜라이브TV 경기", logo: "https://iptv-org.github.io/logos/languages/kor/DLive.png", streamUrl: "http://112.214.255.233/hls/ch02/playlist.m3u8", category: "기타", description: "지역 생활 정보", quality: "HD" },
  { id: "knou", name: "방송대학TV", logo: "https://iptv-org.github.io/logos/languages/kor/KNOUTV.png", streamUrl: "https://live.knou.ac.kr/knou1/live1/playlist.m3u8", category: "기타", description: "언제 어디서나 평생 교육", quality: "HD" },
  { id: "welfare_tv", name: "복지TV", logo: "https://iptv-org.github.io/logos/languages/kor/WelfareTV.png", streamUrl: "http://hls.midibus.kinxcdn.com/live/ch_19b36d47/19b81079d4dfc4f7/playlist.m3u8", category: "기타", description: "따뜻한 복지 소식", quality: "HD" },
  { id: "iscs_tv", name: "서경방송", logo: "https://iptv-org.github.io/logos/languages/kor/SCS.png", streamUrl: "https://live.iscs.co.kr/live/1080p.stream/playlist.m3u8", category: "기타", description: "지역 종합 정보", quality: "HD" },
  { id: "rtv", name: "시민방송 RTV", logo: "https://iptv-org.github.io/logos/languages/kor/RTV.png", streamUrl: "https://rtv-stream.a04f922e9e85c8d25ebfeae3dfd22a67.com/hls/rtv_1080/index.m3u8", category: "기타", description: "열린 채널 시민 방송", quality: "HD" },
  { id: "arirang_tv", name: "Arirang TV", logo: "https://iptv-org.github.io/logos/languages/kor/ArirangTV.png", streamUrl: "http://amdlive-ch01.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8", category: "기타", description: "글로벌 한류 채널", quality: "HD" },
  { id: "arirang_radio", name: "Arirang 라디오", logo: "https://iptv-org.github.io/logos/languages/kor/ArirangTV.png", streamUrl: "http://amdlive-ch03.ctnd.com.edgesuite.net/arirang_3ch/smil:arirang_3ch.smil/playlist.m3u8", category: "Radio", description: "글로벌 라디오", quality: "HD" },
  { id: "jjc", name: "지방자치TV", logo: "https://iptv-org.github.io/logos/languages/kor/JJCTv.png", streamUrl: "https://jjctv.ecn.cdn.infralab.net/jjctv/live/playlist.m3u8", category: "기타", description: "지방 자치 전문 정보", quality: "HD" },
  { id: "channel_i", name: "채널i", logo: "https://iptv-org.github.io/logos/languages/kor/Channeli.png", streamUrl: "http://1.201.160.177:1935/live/myStream/playlist.m3u8", category: "기타", description: "산업 기술 전문", quality: "HD" },
  { id: "nbs", name: "한국농업방송", logo: "https://iptv-org.github.io/logos/languages/kor/NBS.png", streamUrl: "https://media.joycorp.co.kr:4443/live/live_360p/playlist.m3u8", category: "기타", description: "농업/농촌 전문", quality: "HD" },
  { id: "abn", name: "ABN 아름방송", logo: "https://iptv-org.github.io/logos/languages/kor/ABN.png", streamUrl: "https://vod2.abn.co.kr/IPHONE/abn.m3u8", category: "기타", description: "성남 지역 채널", quality: "HD" },
  { id: "ccstv", name: "CSS 충북방송", logo: "https://iptv-org.github.io/logos/languages/kor/CCS.png", streamUrl: "https://media.ccstv.co.kr:1936/OnAirEdge/OnAir/playlist.m3u8", category: "기타", description: "지역 정보 채널", quality: "HD" },
  { id: "kctv_gj_05", name: "KCTV 광주 CH05", logo: "https://iptv-org.github.io/logos/languages/kor/KCTVGwangju.png", streamUrl: "http://119.77.96.184:1935/chn05/chn05/playlist.m3u8", category: "기타", description: "지역 방송", quality: "HD" },
  { id: "kctv_gj_21", name: "KCTV 광주 CH21", logo: "https://iptv-org.github.io/logos/languages/kor/KCTVGwangju.png", streamUrl: "http://119.77.96.184:1935/chn21/chn21/playlist.m3u8", category: "기타", description: "지역 방송", quality: "HD" },
  { id: "kctv_jj_07", name: "KCTV 제주 CH07", logo: "https://iptv-org.github.io/logos/languages/kor/KCTVJeju.png", streamUrl: "https://vod.kctvjeju.com/LIVE/ch7/playlist.m3u8", category: "기타", description: "지역 방송", quality: "HD" },
  { id: "kctv_jj_20", name: "KCTV 제주 CH20", logo: "https://iptv-org.github.io/logos/languages/kor/KCTVJeju.png", streamUrl: "https://vod.kctvjeju.com/ch7/ch4/playlist.m3u8", category: "기타", description: "지역 방송", quality: "HD" },
  { id: "ktv", name: "KTV 국민방송", logo: "https://iptv-org.github.io/logos/languages/kor/KTV.png", streamUrl: "https://hlive.ktv.go.kr/live/klive_h.stream/playlist.m3u8", category: "기타", description: "정부 정책 및 생활 정보", quality: "HD" },
  { id: "nhtv", name: "NHTV 농협방송", logo: "https://iptv-org.github.io/logos/languages/kor/NHTV.png", streamUrl: "http://nonghyup.flive.skcdn.com/nonghyup/_definst_/nhlive/playlist.m3u8", category: "기타", description: "농협 전문 채널", quality: "HD" },
  { id: "obs", name: "OBS 경인", logo: "https://iptv-org.github.io/logos/languages/kor/OBS.png", streamUrl: "https://vod.obs.co.kr:444/live/obsstream1/tv.stream/playlist.m3u8", category: "기타", description: "지역 중심 채널", quality: "HD" },
  { id: "obs_radio", name: "OBS 경인라디오", logo: "https://iptv-org.github.io/logos/languages/kor/OBS.png", streamUrl: "https://vod.obs.co.kr:444/live/obsstream1/radio.stream/playlist.m3u8", category: "Radio", description: "경인 전문 라디오", quality: "HD" },
  { id: "tbs_tv", name: "tbs TV", logo: "https://iptv-org.github.io/logos/languages/kor/TBS.png", streamUrl: "https://cdntv.tbs.seoul.kr/tbs/_definst_/tbs_tv_web_720.smil/playlist.m3u8", category: "기타", description: "시민의 눈과 귀", quality: "HD" },
  { id: "tbs_fm", name: "tbs FM", logo: "https://iptv-org.github.io/logos/languages/kor/TBS.png", streamUrl: "https://cdnfm.tbs.seoul.kr/tbs/_definst_/tbs_fm_web_360.smil/playlist.m3u8", category: "Radio", description: "생활 라디오", quality: "HD" },
  { id: "tbs_efm", name: "tbs eFM", logo: "https://iptv-org.github.io/logos/languages/kor/TBS.png", streamUrl: "https://cdnefm.tbs.seoul.kr/tbs/_definst_/tbs_efm_web_720.smil/playlist.m3u8", category: "Radio", description: "글로벌 라디오", quality: "HD" },
  
  { id: "ytn", name: "YTN NEWS", logo: "https://iptv-org.github.io/logos/languages/kor/YTN.png", streamUrl: "https://www.youtube-nocookie.com/embed/aZyD6EPl6KU?autoplay=1&enablejsapi=1&rel=0", category: "기타", description: "24시간 뉴스 채널", quality: "FHD" },
  { id: "yonhap", name: "Yonhap News TV", logo: "https://iptv-org.github.io/logos/languages/kor/YonhapNewsTV.png", streamUrl: "https://www.youtube-nocookie.com/embed/6QZ_qc75ihU?autoplay=1&enablejsapi=1&rel=0", category: "기타", description: "대한민국 대표 뉴스 채널", quality: "FHD" },

  // --- Debug ---
  {
    id: "test",
    name: "SIGNAL TEST",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/SMPTE_Color_Bars.svg/1024px-SMPTE_Color_Bars.svg.png",
    streamUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    category: "Debug",
    description: "플레이어 상태 점검을 위한 테스트 스트림입니다.",
    quality: "UHD",
  },
];
